//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import UIKit

class CoreData___VARIABLE_sceneName___Worker:___VARIABLE_sceneName___WorkerProtocol {
    
    /*
    func getMovies(ofPage page: Int, completionHandler: @escaping (() throws -> [MovieModel]) -> Void) {
        
        let fetch:NSFetchRequest<Movie> = Movie.fetchRequest()
        do{
            
            let movies = try CoreDataManager.sharedInstance.persistentContainer.viewContext.fetch(fetch)
            var moviesModel:[MovieModel] = []
            for movie in movies{
                let model = movie.getModel()
                moviesModel.append(model)
            }
            
            completionHandler{ return moviesModel }
        }catch{
            completionHandler{ throw error }
        }
    }
     */
}
