//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import Foundation

class ___VARIABLE_sceneName___Worker{
    
    var worker:___VARIABLE_sceneName___WorkerProtocol
    
    init(worker:___VARIABLE_sceneName___WorkerProtocol) {
        self.worker = worker
    }
    
    /*
    func getMovies(ofPage page:Int, completionHandler:@escaping (([MovieModel]?,Error?) -> Void)){
        
        worker.getMovies(ofPage: page) { (movies:() throws -> [MovieModel]) in
            
            do {
                let movies = try movies()
                completionHandler(movies,nil)
            }catch let error{
                completionHandler(nil,error)
            }
        }
    }
     */
}


protocol ___VARIABLE_sceneName___WorkerProtocol{
//    métodos necessários
//    func getMovies(ofPage page:Int, completionHandler:@escaping (() throws -> [MovieModel]) -> Void)
}
