//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import UIKit

class Network___VARIABLE_sceneName___Worker:___VARIABLE_sceneName___WorkerProtocol {
    
    /*
    func getCategories(completionHandler: @escaping (() throws -> [CategoryModel]) -> Void) {
        
        let request = ___PROJECTNAME___Requests.<#request#>
        
        ServiceManager().request(withURL: request) { (data,response,error) in
            
            if error == nil, let data = data {
                
                do{
                    let decoder = JSONDecoder()
                    decoder.keyDecodingStrategy = .convertFromSnakeCase //já 'elimina' os _
                    let categories = try decoder.decode([CategoryModel].self, from: data)
                    
                    for category in categories {
                        category.saveInCoreData()
                    }
                    
                    completionHandler{ return categories }
                }catch{
                    completionHandler{ throw error }
                }
            }else{
                NSLog("Erro ao tentar recuperar os dados do servidor -> \(error?.localizedDescription ?? "")")
                completed(nil,error)
            }
        }
    }
     */
}
