//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by Toledo's Swift Xcode Templates
//

import Foundation

struct ___VARIABLE_structName___: Codable {
    
    var <#atrib#>: <#type#>
    let <#atrib#>: <#type#>
    
    /* CodingKeys
    enum CodingKeys:String,CodingKey{
        
        case <#atrib#> = ""
    }
     */
    
    /* para implementar esse método é preciso extender o protocol Equatable
    static func == (lhs: ___VARIABLE_structName___, rhs: ___VARIABLE_structName___) -> Bool {
    
        return true
    }
     */
}
